          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/ssh-praktikan3

            echo "Cek folder project"

            if [ ! -d "${HOME}/senpro/518300/modul02/senpro-github-action/" ]; then
              echo "Repository belum di-clone. Cloning..."

              mkdir -p ~/senpro/518300/modul02
              cd ~/senpro/518300/modul02

              git clone https://github.com/Fannysbth/senpro-github-action.git

              cd ~/senpro/518300/modul02/senpro-github-action

              echo "Install Package dan Build Project"
              npm install
              npm run build

            else
              echo "Repository sudah ada. Building..."

              cd ~/senpro/518300/modul02/senpro-github-action

              git restore .
              git pull origin main

              echo "Install Package dan Build Project"
              npm install
              npm run build
            fi 